### ISSUE TITLE
Analogs range - death zone (RG-350)

### ISSUE THREAD

**Issue by donleo72** [gameblabla/pcsx4all#16]
These chinese machines rarely get (-1.0  -  +1.0) in analog tests. Usually they get something like (-0.96  -  +0.97) etc.  So the actual range of the analogs is very stric and most of games do not work properly (walk instead run, etc). It could be nice at a range from -0.90 to +0.90 for the most of these machines.

**Comment by gameblabla** [comment]
Btw, i'm accepting patches for that because i'm still waiting for my console to arrive... Looks like i won't get mine until next month.

**Comment by gameblabla** [comment]
It seems that Tony may have adjusted that kernel side, which would be the right approach.
I'm not sure though, can anyone confirm ?

**Comment by donleo72** [comment]
Its fixed.
