### ISSUE TITLE
pcsx4all final release for RG350, accelerated games problem

### ISSUE THREAD

**Issue by Ninoh-FOX** [gameblabla/pcsx4all#17]
skip bios screen option is missing
Another problem is that games that run well in pcsx4all from stock firmware, in the release opk run to a speed two or four more up of the normal speed.

**Comment by Ninoh-FOX** [comment]
for example Megaman legend saga

**Comment by gameblabla** [comment]
I have no idea what "Skip bios screen option" is, it never existed in PCSX4ALL in its life time.

I'll take a look at MML though but i never heard of that issue from anyone.

**Comment by Ninoh-FOX** [comment]
Sorry, the correct words is "skip BIOS logos"

![](https://fotos.subefotos.com/c135cdf6ecf1c1f6a7736e8afd2ce5edo.jpg)

**Comment by gameblabla** [comment]
Oh right, nice catch. For some reasons, it got removed from the frontend at some point...
I'll fix that up

**Comment by gameblabla** [comment]
Skip BIOS logos is now available again in the new OPK release.

As for the speedup issue, i believe its either :
- You did not turn on the frame limiter in GPU settings
- HLE is turned on. (some games suffer from speed issues over HLE)
- Something else

**Comment by Ninoh-FOX** [comment]
I have HLE emulated BIOS OFF (I use pal bios) and Frame limiter ON
If I use your config is the same, overspeed, the stock emulator don't has the speed problem. (Game test Megaman Legend 1 and 2 usa)
A bug the your last release, Skip BIOS logos not save the changes, if you relaunch the emulator, is alwais in ON.
Thanks for you work!!

**Comment by Ninoh-FOX** [comment]
This is the config file generated from your emulator
`CONFIG_VERSION 0
Xa 0
Mdec 0
PsxAuto 1
Cdda 0
HLE 0
RCntFix 0
VSyncWA 0
Cpu 0
PsxType 1
SpuIrq 0
SyncAudio 0
SpuUpdateFreq 2
ForcedXAUpdates 1
ShowFps 0
FrameLimit 1
FrameSkip 0
AnalogArrow 0
Analog_Mode 2
SpuUseInterpolation 0
SpuUseReverb 0
SpuVolume 1024
CycleMultiplier 200
interlace 0
clip_368 0
lighting 1
fast_lighting 1
blending 1
dithering 0
LastDir /usr/local/home/.pcsx4all
BiosDir /media/data/local/home/.pcsx4all/bios
Bios PSX - SCPH7502.BIN`

this is from stock:

`CONFIG_VERSION 0
Xa 0
Mdec 0
PsxAuto 1
Cdda 0
HLE 0
SlowBoot 1
RCntFix 0
VSyncWA 0
Cpu 0
PsxType 1
SpuIrq 0
SyncAudio 1
SpuUpdateFreq 2
ForcedXAUpdates 1
ShowFps 0
FrameLimit 1
FrameSkip 0
SpuUseInterpolation 0
SpuUseReverb 0
SpuVolume 1024
CycleMultiplier 200
interlace 0
pixel_skip 0
lighting 1
fast_lighting 1
blending 1
dithering 1
LastDir /usr/local/home/.pcsx4all
BiosDir /media/data/local/home/.pcsx4all/bios
`
your emulator not make SlowBoot option.

another is that power button not work for me for open the menu, is START+SELECT

Analogics sticks now works fine. MGS now work, no more crazy stick.

**Comment by gameblabla** [comment]
ah yes, it appears that whoever did the port.c code also removed saving Skipping BIOS from config, which is very annoying and it means that it won't save the setting. I'll look into it (and the power button issue)

**Comment by Ninoh-FOX** [comment]
Thanks

**Comment by Ninoh-FOX** [comment]
L3 and R3 buttons not work.

**Comment by gameblabla** [comment]
@Ninoh-FOX Yeah it turns out those buttons were mapped to something else because dumb people could not tell me what they were mapped to in SDL, this is fixed in the minor OPK release.

Power button still won't work though, because it seems that SDL does not map it to anything !

**Comment by Ninoh-FOX** [comment]
@gameblabla yeah, now work fine.

Please, see this file about case from Power button, in ReGBA work.

https://github.com/Nebuleon/ReGBA/blob/master/source/opendingux/od-input.c

**Comment by gameblabla** [comment]
[https://cdn.discordapp.com/attachments/591092177887690866/632363927166255145/pcsx4all.opk](https://cdn.discordapp.com/attachments/591092177887690866/632363927166255145/pcsx4all.opk)

I've uploaded a build on discord, let me know if this fixes the power button menu issue or not.
If you tell me that ReGBA works with the menu button then i hope it will work here.

**Comment by Ninoh-FOX** [comment]
yes, now work!!

**Comment by Ninoh-FOX** [comment]
now only is fix the ultraspeed problem in some games and add rumble XD

Great work @gameblabla

**Comment by gameblabla** [comment]
Rumble actually does not work properly in the current firmware : once you activate it, it never stops.
But the code is there for vibration so if it gets fixed it will be easy to add.

**Comment by Ninoh-FOX** [comment]
Nop. the last kernel fix this

I can test this with MGS if you wish.

**Comment by gameblabla** [comment]
Really ? Well i was not informed of the fix then, will implement asap. Thanks for informing me

**Comment by Ninoh-FOX** [comment]
Yes in this kernel

![](https://fotos.subefotos.com/a1f79e812be6bd5677743777511b337bo.jpg)

@gameblabla See this, this is the code for hwtest that work with rumble to start the app (strong) and push R1+L1 (low)

https://github.com/tonyjih/input-test-rg350

**Comment by gameblabla** [comment]
It uses SDL2 for rumbling though, not something like libshake.
I added libshake support to my build but it was reportedly buggy like on the GCW0.
Maybe there's a bug in libshake, i have no idea...

Also switching to SDL2 is out of question because i'm afraid the extra overhead of SDL2 will hurt performance.

**Comment by Ninoh-FOX** [comment]
Oh, I understand, the controls test application really is very light.

please see this, is SDL2 too, but maybe... https://github.com/jamesofarrell/hocoslamfy/commit/f60f367938321f0bd5cf355c5721905bc5c41812

**Comment by Ninoh-FOX** [comment]
Hi @gameblabla , new update and new kernel, GR350 has now new sdl drives, for rumble see this please.

https://github.com/tonyjih/input-test-rg350/blob/master/sdl.c

**Comment by gameblabla** [comment]
Yeah i just realized that they made a new PCSX4ALL fork with numerous changes.
Unfortunately, they did not bring all of the changes so some games will not work on that version...
I'm working towards bringing some of the changes back to my fork while still keeping support for the RS-97.

**Comment by gameblabla** [comment]
https://cdn.discordapp.com/attachments/591092177887690866/635539341141344257/pcsx4all.opk

Let me know if this crashes on your device. This uses the hardware IPU scaler.

**Comment by Ninoh-FOX** [comment]
@gameblabla  not work, when I load a game, the emulator not start.

your Makefile.gcw0 not work for me. I have this error.

`Compiling src/r3000a.c...
mipsel-linux-gcc: error: no se reconoce la opción de línea de órdenes ‘-mframe-header-opt’
Makefile.gcw0:206: recipe for target 'obj/r3000a.o' failed
make: *** [obj/r3000a.o] Error 1`

if I change from your makefile.gcw0  this:

`ifdef GCC_NEW
 CFLAGS += -mno-abicalls -mframe-header-opt -fno-PIC -mno-check-zero-division -flto
endif`

for this:

`ifdef GCC_NEW
 CFLAGS += -mno-abicalls -std=c99 -fno-PIC -mno-check-zero-division -flto
 endif`

them I can compiler, but your last code has a fail in **char cheatsdir[PATH_MAX];** from

port.c and port.h

> Linking pcsx4all...
> src/port/sdl/port.h:19:13: aviso: el tipo de ‘cheatsdir’ no coincide con la declaración original
>  extern char cheatsdir[PATH_MAX];
>              ^
> src/port/sdl/port.c:122:6: nota: se declaró previamente aquí
>  char cheatsdir[PATH_MAX];
>       ^
> /opt/gcw0-toolchain/usr/lib/gcc/mipsel-gcw0-linux-uclibc/4.9.1/../../../../mipsel-gcw0-linux-uclibc/bin/ld: obj/cdriso.o (symbol from plugin): undefined reference to symbol 'pthread_create'
> /opt/gcw0-toolchain/usr/lib/gcc/mipsel-gcw0-linux-uclibc/4.9.1/../../../../mipsel-gcw0-linux-uclibc/bin/ld: note: 'pthread_create' is defined in DSO /opt/gcw0-toolchain/usr/mipsel-gcw0-linux-uclibc/sysroot/lib/libpthread.so.0 so try adding it to the linker command line
> /opt/gcw0-toolchain/usr/mipsel-gcw0-linux-uclibc/sysroot/lib/libpthread.so.0: could not read symbols: Invalid operation
> collect2: error: ld devolvió el estado de salida 1
> Makefile.gcw0:202: recipe for target 'pcsx4all' failed
> make: *** [pcsx4all] Error 1
> 

The code of the last week, I can compiled well with the change in makefile.gcw0, and work the opk.

**Comment by Ninoh-FOX** [comment]
The log file from you opk

>

> Running PCSX Version 1.9 (Oct 20 2019).
> mipsrec: Initializing
> Mapping/mirroring 2MB recRAM using POSIX shared mem
>  ..mapped to 0x20000000
> Mapping 512KB recROM using mmap
>  ..mapped to 0x20c00000
> Mapping/mirroring 2MB PSX RAM using POSIX shared mem
>  ..mapped to 0x10000000
> Mapping 8MB Expansion ROM + 64KB PSX HW I/O regions using mmap
>  ..mapped to 0x1f000000
> Loading memory card /usr/local/home/.pcsx4all/memcards/mcd001.mcr
> Loading memory card /usr/local/home/.pcsx4all/memcards/mcd002.mcr
> Created SDL audio output semaphore successfully.
> selected sound output driver: sdl
> -> SPU plugin 'spu_pcsxrearmed' initialized successfully.
> -> SPU plugin using configuration settings:
>     Volume:             1024
>     Disabled (-silent): 0
>     XAPitch:            0
>     UseReverb:          0
>     UseInterpolation:   1 (simple)
>     Tempo:              1
>     UseThread:          0
>     UseFixedUpdates:    1
>     SyncAudio:          1
> Loaded CD Image: /media/sdcard/ROMS/PS/Alundra.PBP[pbp].
> Track 01 (DATA) - Start 00:02:00, Length 27:17:21
> Plugins loaded.
> Loaded BIOS image: /media/data/local/home/.pcsx4all/bios/PSX - SCPH1001.BIN

If I run the compiled opk with your last week code

>

>  Running PCSX Version 1.9 (Oct 20 2019).
> mipsrec: Initializing
> Mapping/mirroring 2MB recRAM using POSIX shared mem
>  ..mapped to 0x20000000
> Mapping 512KB recROM using mmap
>  ..mapped to 0x20c00000
> Mapping/mirroring 2MB PSX RAM using POSIX shared mem
>  ..mapped to 0x10000000
> Mapping 8MB Expansion ROM + 64KB PSX HW I/O regions using mmap
>  ..mapped to 0x1f000000
> Loading memory card /usr/local/home/.pcsx4all/memcards/mcd001.mcr
> Loading memory card /usr/local/home/.pcsx4all/memcards/mcd002.mcr
> Created SDL audio output semaphore successfully.
> selected sound output driver: sdl
> -> SPU plugin 'spu_pcsxrearmed' initialized successfully.
> -> SPU plugin using configuration settings:
>     Volume:             1024
>     Disabled (-silent): 0
>     XAPitch:            0
>     UseReverb:          0
>     UseInterpolation:   1 (simple)
>     Tempo:              1
>     UseThread:          0
>     UseFixedUpdates:    1
>     SyncAudio:          1
> Loaded CD Image: /media/sdcard/ROMS/PS/Alundra.PBP[pbp].
> Track 01 (DATA) - Start 00:02:00, Length 27:17:21
> Plugins loaded.
> Loaded BIOS image: /media/data/local/home/.pcsx4all/bios/PSX - SCPH1001.BIN
> CD-ROM Label: PLAYSTATION                     
> CD-ROM ID: SLES01258
> CD-ROM EXE Name: SLES_012.58;1
> Looking for patch /usr/local/home/.pcsx4all/patches/SLES_012.58
> Running ISO image: /media/sdcard/ROMS/PS/Alundra.PBP.
> res change hres: 640   vres: 480   depth: 15   ilace_mask: 1
> res change hres: 256   vres: 240   depth: 15   ilace_mask: 0
> res change hres: 640   vres: 240   depth: 15   ilace_mask: 0
> res change hres: 256   vres: 240   depth: 15   ilace_mask: 0
> res change hres: 640   vres: 480   depth: 15   ilace_mask: 1
> mipsrec: Shutting down
>

**Comment by gameblabla** [comment]
Yes its supposed to be compiled with my statically toolchain. I'll issue a fix for the older toolchain.
Good to know that the OPK works

**Comment by Ninoh-FOX** [comment]
Yes, but the opk that your send me not work

**Comment by gameblabla** [comment]
This is very frustrating as it works under the emulator but not on the real device and i have no means to test it.

**Comment by Ninoh-FOX** [comment]
I understand

this is my toolchain opendingux-gcw0-toolchain.2019-10-20.tar.bz2
https://mega.nz/#!z8x0XK5S!OXmHGToJgvNbzfA3EiBXT_4I9cJSf6wUlxRK7VZv8nU

**Comment by gameblabla** [comment]
Great, i don't have to compile it myself lol...

I found some other issues in my code though, including one that could crash it.
https://cdn.discordapp.com/attachments/591092177887690866/635951698032197633/pcsx4all.opk
If you wanna try it again i'm curious to know.

**Comment by Ninoh-FOX** [comment]
yes, I go to test the opk

See this for compiler the toolchain, because is in continuous updates

https://github.com/podulator/OpenDinguxBuilder

EDIT: @gameblabla works fine, but... Is the HW screen scale, you need an option for resize the screen to SW.

![](https://cdn.discordapp.com/attachments/624204659728318464/635508028770091029/IMG_20191020_180111.jpg)

EDIT2: It is worse than I thought XD XD

https://drive.google.com/file/d/16kZzqUvBy5uqFpvhWJTRC4wIbF17gOuy/view?usp=sharing

**Comment by gameblabla** [comment]
Yes, its the hardware one. I tried to make it force to use fullscreen instead of force aspect but it seems to not work on the RG-350 firmware. It's supposed to be triggered with Power + A.
I guess Tony has not yet merged support for it.
Honestly for conveniance sake i might as well stick with software unless Tony adds fullscreen scaling instead of Keep Aspect.

EDIT : Hmmm it seems that he has not removed it...
Maybe the path changed ? It was /sys/devices/platform/jz-lcd.0/keep_aspect_ratio on the GCW0.

EDIT2: Here's a build with just the software scaler instead
https://cdn.discordapp.com/attachments/591092177887690866/635965236205191168/pcsx4all.opk

Once i figure out how to force fullscreen scaling, then i'll switch to HW IPU scaler.

**Comment by Ninoh-FOX** [comment]
Hmmm I don't now, He make the new kernel with drivers hardware BGR switch from GCW0 and two test psx emulator, HW scaler and SW scaler

I prefer for now SW scaler. Too make a new Regba build with the new driver, and only work no scaler o HW, in this HW is better.

**Comment by gameblabla** [comment]
Hmm i've been told that Power + Y could affect the HW scaler setting but of course, i don't have the thing so no idea there...
That scale issue is real bad, what game is it ?

**Comment by Ninoh-FOX** [comment]
Castlevania X

EDIT: I go to test again

EDIT2: Now work fine, any more to tester? Rumble? XD

EDIT3: well, the speed video/sound is better that the beta PS SW (with the new driver the sound jump a little in some games/scenes/parts , but in your version a little better, hmmmm 95% quality maybe),  great

**Comment by gameblabla** [comment]
It looks like the IPU does not like some screen sizes then because it works fine on my PC with HW_SCALER.

> EDIT2: Now work fine, any more to tester? Rumble? XD

Does Castlevania work properly on the SW one ?
As for Rumble... i couldn't make it work properly in Ape Escape and someone else reported that it would not stop vibrating when enabled...

> well, the speed video/sound is better that the beta PS SW, great

You can thank my toolchain for that. it's going to run even faster once i can PGO it.

Alright i'm going to make it the new stable version then.

**Comment by Ninoh-FOX** [comment]
hardware test has a chain of events where you can control the strong or weak vibration, leave the message code above, and I think it uses SDL

https://github.com/tonyjih/input-test-rg350/blob/master/sdl.c

I think that the better game for test this is Metal Gear Solit, because in options you can test the two rumbles motor

EDIT: When I compiled your code three days ago, the sound and video of the emulator was very clean. In fact it is the one I use except for games that have a 200% speed failure, which are going well in HW / SW version

EDIT2: Your HW / SW version run 200% speed...

**Comment by gameblabla** [comment]
It uses SDL 2, not SDL 1 used here. I think its an issue with libshake which is GCW0/RG350 specific.
Really sucks balls.

> EDIT2: Your HW / SW version run 200% speed...

I'm starting to think that it's maybe an issue with my SDL patches to my toolchain. (vsync not being enabled properly)
I should take a more careful approach then.

Oh you did say it happened even when you compiled it... yet it does not happen on Tony's ?

**Comment by Ninoh-FOX** [comment]
> Alright i'm going to make it the new stable version then.

thanks

> I should take a more careful approach then.

Thanks again XD

> Oh you did say it happened even when you compiled it... yet it does not happen on Tony's ?

Nop, In tony build all game run to 100% speed

EDIT: He has a fork from your code in his RG350_builroot, but I don't test compile

https://github.com/tonyjih/RG350_buildroot/tree/opendingux-2014.08/package/pcsx4all

hmmm only is a script for download and compiler your code...

This is the that I have compiled because it has a better speed video/sound (note: cmake result opk is veeeeery slow game play and this version compiled with Makefile.gcw0 (I changed -frame-header-opt for -std=c99) not fix 200% speed games) 
https://github.com/gameblabla/pcsx4all/commit/17decde5c01bb68f1136843e2c2b2322c4d5191f

**Comment by Ninoh-FOX** [comment]
In you https://github.com/gameblabla/pcsx4all/tree/7 your fix 200% speed games, but, now the framerate is 30~35/60

**Comment by gameblabla** [comment]
That should be fixed by now. It was a compiler issue. Get the latest build from : 
[https://gameblabla.nl/files/ipk/gcw0/](https://gameblabla.nl/files/ipk/gcw0/)
