### ISSUE TITLE
Cheat support on RS-97??

### ISSUE THREAD

**Issue by abelogan** [gameblabla/pcsx4all#23]
Is there any way to get cheat support on the RS-97?  I'm on version 3.0 btw.

Thanks!

**Comment by gameblabla** [comment]
I have added cheat version but not to this version of PCSX4ALL.
https://gameblabla.nl/files/ipk/rs97/

**Comment by abelogan** [comment]
Does that mean if I download the version you provided a link to, I can use cheats?

**Comment by gameblabla** [comment]
Yes
