### ISSUE TITLE
Pcsx4all freezes on 3 games (hard reset needed)

### ISSUE THREAD

**Issue by citral23** [gameblabla/pcsx4all#33]
Formula 1
Formula 1 Championship Edition (aka f1 97)
Formula One 2000

None makes it past the menus, pcsx freezes at the beginning of a race no more response from any button.

Doesn't seem to be fork dependant, replicated on 3 various pcsx4all forks

Stock firmware

**Comment by gameblabla** [comment]
https://github.com/senquack/pcsx4all/commit/541f00ba07baaaec467ae61be32b66a92e534023

It is a known issue, those games are doing some cache trickery. It crashes even on PCSX Rearmed (not on x86_64 though).
F1 99 and F1 2001 should work though. The other alternative is to use the interpreter but that might be slow.

Sorry but if you really want to play those games, you will need to wait for senquack's upcoming PCSX4ALL branch with MXU support.

**Comment by citral23** [comment]
Thank you
